name = "persistence-wallet"
type = "webpack"
compatibility_date = "2024-01-01"
account_id = "1b234fd75823c727716b84645046a3ff"
main = "workers-site/index.js"
site = {bucket = "./build"}
workers_dev = false


[env.testnet-staging]
routes = ["https://test-core-2.wallet.persistence.one/*"]

[env.mainnet-staging]
routes = ["https://staging.wallet.persistence.one/*"]

[env.release]
routes = ["https://wallet.persistence.one/*"]
