export const TX_MIGRATE_AMOUNT_SET = 'TX_MIGRATE_AMOUNT_SET';
export const TX_MIGRATE_ADDRESS_SET = 'TX_MIGRATE_ADDRESS_SET';
export const TX_MIGRATE_MEMO_SET = 'TX_MIGRATE_MEMO_SET';
export const TX_MIGRATE_MODAL_SHOW = 'TX_MIGRATE_MODAL_SHOW';
export const TX_MIGRATE_MODAL_HIDE = 'TX_MIGRATE_MODAL_HIDE';
