export const TX_TOKENIZE_AMOUNT_SET = 'TX_TOKENIZE_AMOUNT_SET';
export const TX_TOKENIZE_MEMO_SET = 'TX_TOKENIZE_MEMO_SET';
export const TX_TOKENIZE_MODAL_SHOW = 'TX_TOKENIZE_MODAL_SHOW';
export const TX_TOKENIZE_MODAL_HIDE = 'TX_TOKENIZE_MODAL_HIDE';

