name: "Build and upload IPFS"
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/checkout@v3
      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.3.1
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET }}
          pinName: echo "pWallet ${{ github.event.tag.name }}"
