---
name: Release

on:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: npm run build --if-present
      env:
        REACT_APP_API_KEY: 'https://rest.core.persistence.one'
        REACT_APP_TENDERMINT_RPC_ENDPOINT: 'https://rpc.core.persistence.one'
        REACT_APP_WEBSITE_URL: 'https://wallet.persistence.one'
        REACT_APP_EXPLORER_API: 'https://www.mintscan.io/persistence'
        REACT_APP_MAIL_CHIMP_URL: 'https://one.us17.list-manage.com/subscribe/post?u=fd70c7f5c39a43acbedb49253&amp;id=7f8e2dbc48'
        REACT_APP_CHAIN_ID: 'core-1'
        REACT_APP_CHAIN_NAME: 'Persistence'
        REACT_APP_IBC_CONFIG: 'ibcMainnet.json'
        REACT_APP_GA_TRACKING_ID: 'G-XQ9NQJL11L'
        REACT_APP_SENTRY_API: 'https://a31c61f5ce774e0791ffdc3b830b406c@o1083089.ingest.sentry.io/6092403'
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        environment: 'release'

  upload-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.3.1
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET }}
          pinName: echo "pWallet ${{ github.event.release.name }}"
