name: "Upload IPFS Readme"
on:
  push:
    tag:
      - 'v*'

jobs:
  upload-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.3.1
        id: upload
        with:
          path: ./artifact
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET }}
          pinName: echo "pWallet ${{ github.event.tag.name }}"
          verbose: true
